### ISSUE TITLE
HtmlResponse

### ISSUE THREAD

**Issue by mohd7469** [actions-on-google/actions-builder-conversation-components-nodejs#1]
what about HtmlResponse for canvas project?

**Comment by mohd7469** [comment]
![image](https://user-images.githubusercontent.com/12613564/97234133-081c3680-1802-11eb-8d52-e597757fdd22.png)

**Comment by taycaldwell** [comment]
Hi @awais786327,

We have a code sample demonstrating Interactive Canvas for Actions Builder [here](https://github.com/actions-on-google/actions-builder-canvas-nodejs/blob/master/sdk/webhooks/ActionsOnGoogleFulfillment/index.js#L56)

`Canvas` response (Actions Builder) is the equivalent of `HtmlResponse` (Dialogflow).

**Comment by taycaldwell** [comment]
That sample also demonstrates how to properly read surface capabilities from your webhook when using the Actions Builder client library.

**Comment by mohd7469** [comment]
@taycaldwell one more question, how can we use RichResponse in @assistant/conversation? I don't see any documentation regarding this anywhere

**Comment by taycaldwell** [comment]
Hey @awais786327,

You can read about how to use the various rich responses [here](https://developers.google.com/assistant/conversational/prompts-rich).

Snippets that use the @assistant/conversation library are provided in the Node.js webhook tab.
